version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.0
    depends_on:
      - kafka
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
  kafka-ui:
    image: 'landoop/kafka-topics-ui'
    ports:
      - '8000:8000'
    environment:
      - KAFKA_REST_PROXY_URL=rest-proxy:8082
      - PROXY=true
    depends_on:
      - rest-proxy
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
